CREATE TABLE product_details
(
    product_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    amount      DECIMAL,
    quantity    INTEGER                                 NOT NULL,
    category    VARCHAR(255),
    CONSTRAINT pk_product_details PRIMARY KEY (product_id)
);