CREATE TABLE productdetails
(
    productid   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    amount      DECIMAL,
    quantity    INTEGER                                 NOT NULL,
    category    VARCHAR(255),
    CONSTRAINT pk_productdetails PRIMARY KEY (productid)
);