CREATE TABLE cart_items(
  cart_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL ,
  product_id BIGINT REFERENCES product_details(product_id),
  cart_id BIGINT REFERENCES carts(cart_id),
  quantity INT not null ,
  total_price DECIMAL(10,2) not null,
  CONSTRAINT pk_cart_items PRIMARY KEY (cart_item_id)
);